# /etc/rspamd/local.d/multimap.conf (+APPEND)
PMWH3_WHITELIST {
    type = "from";
    prefilter = true;
    action = "accept";
    map = "https://WEBHOST/cevian/pmwh3/filtering/map_wblist/W?key=TOKEN";
}

PMWH3_BLACKLIST {
    type = "from";
    prefilter = true;
    action = "reject";
    map = "https://WEBHOST/cevian/pmwh3/filtering/map_wblist/B?key=TOKEN";
}
