# /etc/rspamd/local.d/settings.conf (+APPEND)
pmwh3_thresholds {
    priority = medium;
    external_map {
        map {
            external = true;
            backend = "https://WEBHOST/cevian/pmwh3/filtering/settings_query?key=TOKEN";
            method = "body";        # NOT 'query' (query would replace ?key=)
            encode = "json";
            timeout = 3.0;
        }
        selector = "id('rcpt');rcpts:addr.lower";
    }
}
